### ISSUE TITLE
Add resolveConfig method to beautifier and use in beautify method

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/beautifier-php-cs-fixer#8]
- [x] Add the resolveConfig method and look for `.php_cs` or `.php_cs.dist` files in the file path or the project path (total of 4 checks)
- [x] Once one is found, return that file's path
- [x] If there is a found config, pass that into the `--config=${beautifierConfig}` flag and remove the `--rules=@PSR2` flag
- [x] If no config is found, don't change anything in the php-cs-fixer call

**Comment by Glavin001** [comment]
Related to https://github.com/Unibeautify/unibeautify/issues/48

**Comment by Glavin001** [comment]
https://github.com/Unibeautify/beautifier-php-cs-fixer/pull/9
